language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
script:
  - "lektor build"
  - 'test "$TRAVIS_PULL_REQUEST" == false && test "$TRAVIS_BRANCH" == dev && lektor deploy ghpages'